### ISSUE TITLE
OSError: [Errno 5] Input/output error:

### ISSUE THREAD

**Issue by zldzmfoq12** [sooftware/KsponSpeech-preprocess#10]
When I preprocess ksponspeech data, I meet OSError: [Errno 5] Input/output error. What can I do to solve this problem. I can't find any solution to this.
Thank you.

**Comment by sooftware** [comment]
Please attach the error log.

**Comment by sooftware** [comment]
한국분이신 것 같은데, 한글로 할게요. 에러 로그 첨부해주시면 어떤 에러인지 파악이 더 쉬울 것 같네요.

**Comment by zldzmfoq12** [comment]
OSError: [Errno 5] Input/output error: '/mnt/nas_A/public/DB/aihub/speech_data/KsponSpeech_01/KsponSpeech_0105'과 같은 에러입니다.

**Comment by zldzmfoq12** [comment]
참고로 서버에서 docker container를 통해 코드를 실행했습니다.

**Comment by zldzmfoq12** [comment]
File "main.py", line 80, in <module>
    main()
  File "main.py", line 62, in main
    audio_paths, transcripts = preprocess(opt.dataset_path, opt.preprocess_mode)
  File "/mnt/hdd_mnt/jsh/KoSpeech/dataset/kspon/preprocess/preprocess.py", line 114, in preprocess
    for jdx, file in enumerate(os.listdir(path)):
OSError: [Errno 5] Input/output error: '/mnt/nas_A/public/DB/aihub/speech_data/KsponSpeech_01/KsponSpeech_0105'

**Comment by sooftware** [comment]
경로지정이 잘못 된게 아닐까 싶네요. 확인해주실래요?

**Comment by zldzmfoq12** [comment]
해결했습니다. 아마 서버의 문제였던 것 같습니다. 답변해주셔서 감사합니다.
