### ISSUE TITLE
file type error

### ISSUE THREAD

**Issue by sayjose** [sooftware/KsponSpeech-preprocess#3]
In my directory, 'pcm' files and 'txt' files are mixed.

So, below code show error(encoding error).

`def create_script(dataset_path, script_prefix):
    print('create_script started..')
    char2id, id2char = load_label('aihub_labels.csv')

    for directory in os.listdir(dataset_path):
        path = os.path.join(dataset_path, directory)
        for file in os.listdir(path):
            sentence, target = None, None

            with open(os.path.join(path, file), "r") as f:
                sentence = f.read()

            with open(os.path.join(path, script_prefix + file[12:]), "w") as f:
                target = sentence_to_target(sentence, char2id)
                f.write(target)`

I think it is better to put one line like below

`def create_script(dataset_path, script_prefix):
    print('create_script started..')
    char2id, id2char = load_label('aihub_labels.csv')

    for directory in os.listdir(dataset_path):
        path = os.path.join(dataset_path, directory)
        if file.endswith('txt'): # like this line`

I use AIhub data.

have a good day.

**Comment by sooftware** [comment]
한국분이신것 같은데 한글로 답변드리겠습니다 !!  
바빠서 글을 제대로 확인해보지는 못했지만, pcm이랑 txt 파일이 섞여서 에러가 나신다는 말씀이 어떤 말씀인지 
정확히 알 수 있을까요?

**Comment by sayjose** [comment]
데이터를 다운받으면 pcm과 txt가 혼재되어 있어 인코딩에러가 발생하였습니다.
txt를 따로 분리해내서 preprocessing을 진행하면 에러가 발생하지 않으나 저 처럼 섞여있으면 에러가 날 수 도 있을 것 같아서 글 남겼습니다!

**Comment by sooftware** [comment]
아 네 지적해주신 부분 감사합니다.  
해당 부분 수정하여 커밋하겠습니다.
